### ISSUE TITLE
Greeter window sometimes doesn't grab focus [$60]

### ISSUE THREAD

**Issue by Djaler** [elementary/greeter#144]
After last greeter updates, I noticed that when I boot into elementary, password input is not in focus

**Comment by darthmaulbr** [comment]
I have the same issue.

**Comment by jiteshsingh** [comment]
same issue but only when login screen appears first time after bootup

**Comment by danrabbit** [comment]
Please do not comment "I have the same issue". Use the :+1: reaction

**Comment by ratza** [comment]
I can confirm that this does not seem to be an issue with the latest version (3.2.0) on boot in Juno. It's still an issue when locking the screen. I didn't even realize how used I got to the fact that on Loki, when locking the session, even though the screen stays off the input is in focus - it allowed me to login without even waiting for the monitor to detect and display the screen.

**Comment by peteruithoven** [comment]
I can only consistently reproduce this issue after Shutdown or Restart. The password field has focus for me after a Lock or Suspend. 

Is there a way for me to debug this? Maybe add some logging to journal?

**Comment by yusren** [comment]
The worst thing on Juno's Login screen is that the keyboard doesn't work until we click on the screen.

**Comment by cassidyjames** [comment]
Confirming and marking as high priority since this affects many users and we're getting a lot of mentions of it on social media.

**Comment by tugcanolgun** [comment]
I can confirm this. This happens in my laptop too.

**Comment by infuerano** [comment]
It is a problem which is annoying.

**Comment by cassidyjames** [comment]
Please do not comment things like, "I have the same issue". Use the :+1: reaction to mark it as affecting you, and/or use the "Subscribe" button to get updates.

**Comment by kt1024** [comment]
maybe this is relevant to #131 , here is what I found:
- on a notebook with single/internal intel video card, the password input box is auto focused. 
- on notebook with 2 video card (intel + nvidia), input box is not focused, and 'unknown display' is always activated. 
above test is done with fresh juno install.

**Comment by seesemichaelj** [comment]
I am able to reproduce this issue consistently on boot and from locking.

I have also found a hotfix that really doesn't address the root problem. At the end of the constructor in [PantheonGreeter.vala](https://github.com/elementary/greeter/blob/master/src/PantheonGreeter.vala#L211), if I add the following code, I can get it to focus the login box automatically after some delay:

```
Timeout.add (5000, () => {
    userlist_actor.get_current_loginbox ().pass_focus ();
    this.get_window ().focus (Gdk.CURRENT_TIME);
    return false;
});
```

While 5 seconds is exaggerated and too long, I did notice small timeouts of less than 500 ms do not work.

This is in no way a solution, but it may be a fix. I'm not sure what the robust version of this is, as we can't really pick some arbitrary timeout that will work for everyone (people have slower machines, etc).

Discussing the "root cause" though, this points to something else is grabbing the focus during initialization or something along those lines. I couldn't get the debugging to work, so I can't do any debugging (like printing things out to the screen of where the current focus is). I tried adding a `*:focus { border-color: red; }` to the CSS and no luck. Only the text box gets outlined when it eventually gets focused.

Any thoughts? I will probably submit some form of a PR later today.

**Comment by peteruithoven** [comment]
I tried changing Exec in the the greeter desktop file to:
```
Exec=bash -c 'G_MESSAGES_DEBUG=all @PROJECT_NAME@ > /tmp/greeter.log 2> /tmp/greeter.log'
```
In the hope to enable some logging but then it fails to boot to the Greeter.
Any tips?

**Comment by seesemichaelj** [comment]
@peteruithoven I actually remembered seeing a log in `/var/log/lightdm`

Turns out lightdm is already outputting the greeter output in `/var/log/lightdm/seat0-greeter.log` (just tested by adding a log and saw the output there post-login)

This may help quite a bit now!

**Comment by peteruithoven** [comment]
Nice! But, unless we add all logging to `critical ()` function we still need to find a way to tweak `G_MESSAGES_DEBUG`.

I've now created the file `/usr/local/bin/greeter-logged` with:
```
#!/bin/bash

G_MESSAGES_DEBUG=all io.elementary.greeter &> /tmp/greeter.log
```
And changed the Exec in `/usr/share/xgreeters/io.elementary.greeter.desktop` to:
```
Exec=/usr/local/bin/greeter-logged
```
We'll see if that helps.

**Comment by peteruithoven** [comment]
That helped: 
Booting logs: https://gist.github.com/peteruithoven/220fa27644614c838b334db800c8d31a (no focus)
Lock logs: https://gist.github.com/peteruithoven/e66e8c8a8b8798b9683f6c646e92379c (focus)

**Comment by seesemichaelj** [comment]
Curious. I'll try this change as well later today to see what I get on lock (since my lock will not focus). Nice find!

Are you on a High DPI screen? My screens are 1080p; I also have a High DPI laptop that I can see what results I get.

**Comment by peteruithoven** [comment]
I tried adding @seesemichaelj timeout focus code to the end of the `monitors_changed`callback, but that made my system stop booting. It must be the `get_window ().focus (Gdk.CURRENT_TIME);` part, because just adding the `userlist_actor.get_current_loginbox ().pass_focus ();` was fine, but doesn't solve the issue. 

``` vala
    void monitors_changed () {
        Gdk.Rectangle geometry;
        get_screen ().get_monitor_geometry (get_screen ().get_primary_monitor (), out geometry);
        resize (geometry.width, geometry.height);
        move (geometry.x, geometry.y);
        reposition ();
        
        userlist_actor.get_current_loginbox ().pass_focus (); // doesn't solve anything
        // get_window ().focus (Gdk.CURRENT_TIME); // stops system from booting to greeter
    }
````

**Comment by seesemichaelj** [comment]
I don't believe it's related to monitors_changed, my monitors_changed happens once at the very start, way before the focus_in/focus_out. Logs: https://gist.github.com/seesemichaelj/c8286820e4958f81cbdc4e636c424d3e

**Comment by riker09** [comment]
I don't know if this is helpful, but my work laptop is hooked up via Display Port and HDMI to two external monitors when I experience this issue. Yesterday I was at home (with my laptop) and the password field was in focus after waking up from screen lock.

The same is true for my home computer (iMac 5k 17,1). When I resume from a locked screen the password field has the focus. Could the external monitors be the culprits?

**Comment by seesemichaelj** [comment]
Actually @riker09, that's a great point. I can verify on a desktop that when I have >1 monitor plugged in, resume on lock does not focus the field, and if I only 1 monitor plugged in, resume on lock does focus the field

I've also added the `on_focus_event` for the `PantheonGreeter` window (e.g. `this.on_focus_event`), and noticed that the window is getting unfocused when the credentials get the focused ripped from them. This insight on multiple monitors may be a clue in the right direction!

**Comment by riker09** [comment]
I'm glad I could provide some helpful information. :slightly_smiling_face: 

I tried changing my primary monitor (which normally is an external dispay) to the build-in laptop display. But that didn't seem to change anything.

**Comment by cassidyjames** [comment]
I am able to reliably reproduce this issue on a HiDPI laptop without any displays connected. However, today I discovered if I click the mouse (anywhere not just in the input), the input will focus. So if someone is waking their laptop by clicking the mouse, they might not be noticing this.

**Comment by seesemichaelj** [comment]
@cassidyjames good point! I have noticed this as well.

I highly believe the window becomes unfocused, which causes the child widget (`credentials`) to become unfocused. But once the window is focused, the `credentials` become focused again

**Comment by seesemichaelj** [comment]
Thanks for the data! This issue seems to have several different symptoms haha

I'm traveling, so I'll continue looking at this next week

**Comment by shroudedcode** [comment]
I'm using two monitors (HDMI and VGA) and can confirm what @riker09 said. I just wanted to add that:

- When I boot up my machine the login screen appears on one monitor while the other one stays black.
  - This is what I expected.
- After I've focussed the unfocussed input, ...
  - This is unexpected and super annoying.
- ... typed in my password and pressed enter, the *weird scaling* described by @riker09 kicks in: the wallpaper is scaled to fill both monitors.
  - This is unexpected, but not a big deal. Still, it makes the "login process" look _unpolished_.
- Then, the correct layout is used, the wallpaper is correctly scaled and the top bar and dock slide in.

I really like Juno so far — great job on this release, guys! :smiley: — but this one thing (the input not being focussed) is very annoying. The *weird scaling* problem has already existed in Loki and doesn't bother me too much.

**Comment by bwat47** [comment]
> * on a notebook with single/internal intel video card, the password input box is auto focused

I saw this issue when I tried juno on my dell xps 13 9360. intel graphics, no external monitor. In my case it seemed 'random'. sometimes when I booted the machine the box would be focused by default, other times it wasn't

**Comment by peteruithoven** [comment]
Sorry, I've tried the gtk branch and I still need to click my mouse anywhere on the screen to get focus.

**Comment by seesemichaelj** [comment]
I can confirm that on lock (I haven't tried on boot yet), I also have to click somewhere on the monitor which has the prompt. Clicking on the monitor does not appear to focus the input, but it becomes focused if I start typing. Clicking on the input directly does appear to focus the input.

**Comment by cassidyjames** [comment]
I can confirm that this is still an issue. It seems like a race condition; sometimes it happens and sometimes it does not, even on the same hardware. Locking and unlocking several times in a row gives me about a 75% reproducibility rate, though. Something I have noticed is that sometimes it takes longer for the greeter to render correctly; I get it drawing in the top-left corner briefly before snapping to the full size. It seems like when that happens, the focus is broken.

So I believe the issue is that there's a race with the greeter window itself sometimes not getting focus; note that this does not have to do with the text input itself, and the left/right arrow keys also do not work when the window is unfocused.

**Comment by 4ugustin** [comment]
@cassidyjames Could WingPanel steal it?

**Comment by janxkoci** [comment]
I still experience this issue (on stable release) with single HD monitor (so no HiDPI) on my 11" netbook. The focus is sometimes there, but I didn't really notice a pattern like "lock=focused, reboot=unfocused" - to me it looks rather random, like the "race" mentioned in https://github.com/elementary/greeter/issues/144#issuecomment-439539263.

However I also experience the issue #178 as I use flatpak (and don't plan to stop), so maybe my particular Greeter is broken in more ways, and so I have focus issues even on single HD monitor.

**Comment by cassidyjames** [comment]
@fabiopicchi do you happen to have Flatpak installed on that system?

**Comment by samermi1** [comment]
I have a two monitors system. I don't have the bug on login screen just on the unlock screen. after activating the guest account, I can now press the down arrow to select the guest account then the up arrow to select my actual account and get the password field focused.

**Comment by janxkoci** [comment]
That's weird - for me the arrows don't work unless the lock screen is in focus, in which case the pasword field already accepts input. I used this trick in Loki but in Juno it works differently (because it's different under the hood).

**Comment by startsts** [comment]
I always face this error,  but clicking mouse at any place (not necessary at password input) makes it get focus.  It's very weird
(Latest Elementary,  Laptop 14' FullHD)

**Comment by 4levels** [comment]
On a fresh install of the latest version, I can see the login input is focussed briefly and then it becomes blurred, as if something else is stealing the focus.
No difference if an external monitor is connected or not..

**Comment by 4levels** [comment]
I got the focus back on the login greeter in the process of debugging a slow bootup caused by an NFS mount in `/etc/fstab` without the `nofail,noauto` mount options.  As soon as I added those mount options for the NFS share, my laptop boots a lof faster (90 seconds faster) and the greeter password input kept it's focus.
I don't know if this is related, but I also disabled the `Networkmanager-wait-online.service` via systemd since it added another 8 seconds..

**Comment by lhorace** [comment]
I like to add something here, reading the thread in entirety. Correct me if I'm wrong, the thread seem to divulge to losing focus on the lock screen apart from the original OP's post. I have a sneaking feeling, when a fix arrives, it fixes one problem while leaving the problem mentioned by shroudedcode unsolved?

> I'm using two monitors (HDMI and VGA)

I have three monitors, HDMI, 2xDVI

> When I **boot up my machine**

> - After I've focussed the unfocussed input, ...
>   - This is unexpected and super annoying.

**Comment by startsts** [comment]
Since it's to difficult to fix, maybe there is a way to make input be focussed using TAB ? It would make the life easier at least for me

**Comment by seesemichaelj** [comment]
make up your mind! :joy:

**Comment by kr428** [comment]
Seems to work for me now. Thanks if it was intentionally fixed. ;)

**Comment by startsts** [comment]
for me it doesnt fixed yet! AcerSwift 3 - 14 pulgadas FullHd (hiDPI)

**Comment by peteruithoven** [comment]
@startsts you have tried the latest code from github right? As in cloned / downloaded it and compiled it yourself.

**Comment by caiohofbauer** [comment]
I have this problem still. Shouldn't password field be in focus when you hit "Tab" at least?
I don't know, maybe it's a way around to solve this under different scenarios and hardwares, etc.
This is a huge hassle for me because I have my thinkpad lid closed connected to a dock, which is connected to a external monitor. When I wake my laptop from Suspend my external monitor stays all black. So I have to pull the lid and select the password field with my cursor and then type the password. If I could just hit "tab" and type my password, I wouldn't have to pull the lid at least. Ideally it would be automatically on the password field, of course. Anyways, do I have to compile this to fix my issue?

**Comment by cassidyjames** [comment]
@caiohofbauer until the new version is released, yes. We're still ironing out any last issues, but the focus issue does appear to be resolved in all of our testing. The instructions are pretty straightforward in the README, but otherwise, you can also just click anywhere on the current greeter to make the password field grab focus.

**Comment by bksubhuti** [comment]
I can confirm this is still happening.  I just recently reinstalled and updated (today).  I have not tweaks or ppa installed.

**Comment by peteruithoven** [comment]
@bksubhuti unless you've compiled the Greeter from source you can't confirm because you're running an "old" version. 
Issues are closed when the issue is fixed in code, not when the version is released with the fix.

**Comment by caiohofbauer** [comment]
@cassidyjames Glad to hear there is a new greeter coming. Oh, that click anywhere feature is pretty clever, that's a fix for me on the short-term. Thank you.

**Comment by janxkoci** [comment]
Just FYI - clicking anywhere on the greeter to get focus doesn't work for me for quite some time. I hope the new version will work for me.

**Comment by murbanowicz** [comment]
@peteruithoven It's great it's fixed in code. When you expect it to be released?

**Comment by gsupp** [comment]
Still experiencing this issue over a year after it was first reported. Will the new greeter be released anytime soon?

**Comment by Blast-City** [comment]
Anyone still having this issue?
I can't seem to replicate it on the new greeter.

**Comment by janxkoci** [comment]
No the new greeter fixed it for me (thanks for bringing it up, I wanted to review the older bugs soon too). There are other issues but this works fine now.

**Comment by gsupp** [comment]
I can confirm the new greeter fixed this for me.

**Comment by Blast-City** [comment]
Unfortunately it seems is not fixed yet. It may not happen as often, but it's still happening.

**Comment by bksubhuti** [comment]
This was so annoying I moved onward to Deepin... in some ways.. thanks.

**Comment by LuisMi1245** [comment]
That happens to me too.

**Comment by sryze** [comment]
Sorry to bump this old thread but it still happens to me on elementary 7 on my laptop - after it wakes up from sleep, the password field often does not get focus, and needs to be clicked.

**Comment by janxkoci** [comment]
Same for me, it recently got even worse. Now after waking up, the background of the greeter is black instead of grey, like it's loading, and when the grey background finally arrives after a few seconds (on a 2020 ultrabook) the focus is lost from the input field.

**Comment by janxkoci** [comment]
For me the login screen used to appear together with mouse cursor, and the cursor always appeared in the same spot, near bottom right corner. So the cursor position was always consistent when login screen appeared.

So what exactly do you mean here, @intp56?

After switching to Manjaro GNOME, I made another observation, possibly relevant. My lock screen started to behave weird after one kernel update, and I noticed I can get correct behaviour of lock screen with older kernels (6.10, or 6.6 LTS) while new kernels are buggy (6.11 or 6.12).

I never even thought kernel could be responsible for such things as glitches in lock screens after waking up from suspend, but apparently they can. (I've no such issue on Debian 12 MATE with 6.12 kernel, so it's DE dependent too.)

**Comment by yellowgh0st** [comment]
Can you both guys specify what GPU do you run?
What driver do you use? Could be related hence the different experience between kernels.
Sent from Proton Mail Android
-------- Original Message --------On 4/1/25 20:32, Jeňa Kočí  wrote:
  For me the login screen used to appear together with mouse cursor, and the cursor always appeared in the same spot, near bottom right corner. So the cursor position was always consistent when login screen appeared.
So what exactly do you mean here, @intp56?
After switching to Manjaro GNOME, I made another observation, possibly relevant. My lock screen started to behave weird after one kernel update, and I noticed I can get correct behaviour of lock screen with older kernels (6.10, or 6.6 LTS) while new kernels are buggy (6.11 or 6.12).
I never even thought kernel could be responsible for such things as glitches in lock screens after waking up from suspend, but apparently they can. (I've no such issue on Debian 12 MATE with 6.12 kernel, so it's DE dependent too.)—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>



janxkoci left a comment (elementary/greeter#144)
For me the login screen used to appear together with mouse cursor, and the cursor always appeared in the same spot, near bottom right corner. So the cursor position was always consistent when login screen appeared.
So what exactly do you mean here, @intp56?
After switching to Manjaro GNOME, I made another observation, possibly relevant. My lock screen started to behave weird after one kernel update, and I noticed I can get correct behaviour of lock screen with older kernels (6.10, or 6.6 LTS) while new kernels are buggy (6.11 or 6.12).
I never even thought kernel could be responsible for such things as glitches in lock screens after waking up from suspend, but apparently they can. (I've no such issue on Debian 12 MATE with 6.12 kernel, so it's DE dependent too.)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/elementary/greeter/issues/144#issuecomment-2770352256",
"url": "https://github.com/elementary/greeter/issues/144#issuecomment-2770352256",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by janxkoci** [comment]
I only run on integrated Intel graphics, nothing fancy.
